# A comment

USE DatabaseName;

CREATE TABLE IF NOT EXISTS TestTable (
  TestTableID MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  SomeText VARCHAR(32) NOT NULL,
  Created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (TestTableID)
) ENGINE=InnoDB;
